server:
  port : 9091
  servlet:
    context-path: /eqa-survey-service
#  ssl:
#    key-alias: datadimens
#    key-store-password: 123456
#    key-store-type: JKS
#    key-store: classpath:datadimens.com.jks
    
#Database configuration
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/eqa_drive
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: eqa-survey-service

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: https://admin:admin@datadimens.com:8761/eureka

logging:
  file:
    path: /home/logs/
    name: ${logging.file.path}/${spring.application.name}.log
  level:
    root: info
      
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true